name: linux

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        compiler: [dmd-latest, ldc-latest, dmd-beta, ldc-beta]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.dub
        key: ${{ runner.os }}-dub-${{ hashFiles('**/dub.json') }}
        restore-keys: |
          ${{ runner.os }}-dub-

    - uses: actions/checkout@v2
      with:
        repository: google/re2
        path: re2
    - name: build-re2
      run: |
        cd re2
        sudo make prefix=/usr install -j

    - uses: dlang-community/setup-dlang@v1
      with:
        compiler: ${{ matrix.compiler }}
    - name: Run tests
      run: dub test -b=unittest-cov

    - name: codecov
      if: ${{ matrix.compiler == 'dmd-latest' }}
      run: bash <(curl -s https://codecov.io/bash)
